// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBERP.HumanResources.Persistence;

#nullable disable

namespace SBERP.HumanResources.Migrations
{
    [DbContext(typeof(HumanResourcesDBContext))]
    partial class HumanResourcesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WorkingHours")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("UX_Attendance_Employee_Date");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.AttendanceUploadLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FailedRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsRolledBack")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RolledBackDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("SuccessRows")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRows")
                        .HasColumnType("int");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AttendanceUploadLogs");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.BloodGroupLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_BloodGroups_Code");

                    b.ToTable("BloodGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A_POS",
                            IsActive = true,
                            Name = "A+",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "A_NEG",
                            IsActive = true,
                            Name = "A-",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "B_POS",
                            IsActive = true,
                            Name = "B+",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "B_NEG",
                            IsActive = true,
                            Name = "B-",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "AB_POS",
                            IsActive = true,
                            Name = "AB+",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "AB_NEG",
                            IsActive = true,
                            Name = "AB-",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "O_POS",
                            IsActive = true,
                            Name = "O+",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "O_NEG",
                            IsActive = true,
                            Name = "O-",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("HeadEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Departments_Code");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments", t =>
                        {
                            t.HasTrigger("TRG_DeleteDepartments");

                            t.HasTrigger("TRG_InsertDepartments");

                            t.HasTrigger("TRG_UpdateDepartments");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-1111-4111-8111-111111111111"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "ADMIN",
                            Description = "Administrative and executive office",
                            IsActive = true,
                            Name = "Administration"
                        },
                        new
                        {
                            Id = new Guid("a2a2a2a2-2222-4222-8222-222222222222"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "HR",
                            Description = "People operations and talent management",
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("a3a3a3a3-3333-4333-8333-333333333333"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "ENG",
                            Description = "Software engineering and development",
                            IsActive = true,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("a4a4a4a4-4444-4444-8444-444444444444"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "FIN",
                            Description = "Accounting, payroll and treasury",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("a5a5a5a5-5555-4555-8555-555555555555"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "OPS",
                            Description = "Day-to-day business operations",
                            IsActive = true,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.DepartmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HeadEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("DepartmentsLog");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Designation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Designations_Name");

                    b.ToTable("Designations", t =>
                        {
                            t.HasTrigger("TRG_DeleteDesignations");

                            t.HasTrigger("TRG_InsertDesignations");

                            t.HasTrigger("TRG_UpdateDesignations");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-4111-8111-111111111111"),
                            Code = "CEO",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 1,
                            IsActive = true,
                            Name = "Chief Executive Officer"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-4222-8222-222222222222"),
                            Code = "MGR",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 4,
                            IsActive = true,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-4333-8333-333333333333"),
                            Code = "TL",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 5,
                            IsActive = true,
                            Name = "Team Lead"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-8444-444444444444"),
                            Code = "SE",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 6,
                            IsActive = true,
                            Name = "Senior Engineer"
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-4555-8555-555555555555"),
                            Code = "SWE",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 7,
                            IsActive = true,
                            Name = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("d6666666-6666-4666-8666-666666666666"),
                            Code = "HRM",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 4,
                            IsActive = true,
                            Name = "HR Manager"
                        },
                        new
                        {
                            Id = new Guid("d7777777-7777-4777-8777-777777777777"),
                            Code = "ACC",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 6,
                            IsActive = true,
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = new Guid("d8888888-8888-4888-8888-888888888888"),
                            Code = "INT",
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 9,
                            IsActive = true,
                            Name = "Intern"
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.DesignationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DesignationsLog");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternatePhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfLeaving")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EmploymentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OfficialEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PassportExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProbationEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Religion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReportingManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_EmployeeCode");

                    b.HasIndex("OfficialEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_OfficialEmail")
                        .HasFilter("[OfficialEmail] IS NOT NULL");

                    b.HasIndex("ReportingManagerId");

                    b.ToTable("Employees", t =>
                        {
                            t.HasTrigger("TRG_DeleteEmployees");

                            t.HasTrigger("TRG_InsertEmployees");

                            t.HasTrigger("TRG_UpdateEmployees");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAddresses");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IbanNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoutingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeBanks");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCertifications");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeEmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternatePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEmergencyContacts");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeExperiences");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLeaving")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EmploymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmployeesLog");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProficiencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmploymentStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_EmploymentStatuses_Code");

                    b.ToTable("EmploymentStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ACTIVE",
                            IsActive = true,
                            Name = "Active",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "ON_LEAVE",
                            IsActive = true,
                            Name = "On Leave",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "SUSPENDED",
                            IsActive = true,
                            Name = "Suspended",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "RESIGNED",
                            IsActive = true,
                            Name = "Resigned",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "TERMINATED",
                            IsActive = true,
                            Name = "Terminated",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "RETIRED",
                            IsActive = true,
                            Name = "Retired",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmploymentTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_EmploymentTypes_Code");

                    b.ToTable("EmploymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FULL_TIME",
                            IsActive = true,
                            Name = "Full Time",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PART_TIME",
                            IsActive = true,
                            Name = "Part Time",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "CONTRACT",
                            IsActive = true,
                            Name = "Contract",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "INTERN",
                            IsActive = true,
                            Name = "Intern",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "CONSULTANT",
                            IsActive = true,
                            Name = "Consultant",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "PROBATION",
                            IsActive = true,
                            Name = "Probation",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.GenderLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Genders_Code");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MALE",
                            IsActive = true,
                            Name = "Male",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "FEMALE",
                            IsActive = true,
                            Name = "Female",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "OTHER",
                            IsActive = true,
                            Name = "Other",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.HRSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnnualLeaveDays")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceSource")
                        .HasColumnType("int");

                    b.Property<bool?>("AutoProcessEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("AutoProcessTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BiometricConnectionString")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("BiometricProvider")
                        .HasColumnType("int");

                    b.Property<string>("BiometricSourceObject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CasualLeaveDays")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("GracePeriodMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeEndTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OfficeStartTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SickLeaveDays")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("WeeklyOffDays")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("HRSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("feed0001-0000-4000-8000-000000000001"),
                            AnnualLeaveDays = 22,
                            AttendanceSource = 1,
                            AutoProcessEnabled = false,
                            AutoProcessTime = "23:30",
                            BiometricProvider = 0,
                            CasualLeaveDays = 5,
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            GracePeriodMinutes = 15,
                            IsActive = true,
                            OfficeEndTime = "17:30",
                            OfficeStartTime = "08:30",
                            SickLeaveDays = 10,
                            WeeklyOffDays = "5,6"
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.MaritalStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_MaritalStatuses_Code");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SINGLE",
                            IsActive = true,
                            Name = "Single",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "MARRIED",
                            IsActive = true,
                            Name = "Married",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "DIVORCED",
                            IsActive = true,
                            Name = "Divorced",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "WIDOWED",
                            IsActive = true,
                            Name = "Widowed",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "SEPARATED",
                            IsActive = true,
                            Name = "Separated",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Attendance", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Department", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Departments_Parent");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Employee", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Employees_Department");

                    b.HasOne("SBERP.HumanResources.Models.Base.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Employees_Designation");

                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "ReportingManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Employees_ReportingManager");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("ReportingManager");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeAddress", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeBank", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithOne("BankInfo")
                        .HasForeignKey("SBERP.HumanResources.Models.Base.EmployeeBank", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeCertification", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeDocument", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeEducation", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Educations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeEmergencyContact", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeExperience", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Experiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeSkill", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.EmployeeTraining", b =>
                {
                    b.HasOne("SBERP.HumanResources.Models.Base.Employee", "Employee")
                        .WithMany("Trainings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SBERP.HumanResources.Models.Base.Employee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankInfo");

                    b.Navigation("Certifications");

                    b.Navigation("DirectReports");

                    b.Navigation("Documents");

                    b.Navigation("Educations");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("Experiences");

                    b.Navigation("Skills");

                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
