using Microsoft.EntityFrameworkCore.Migrations;
using SBERP.Security.Persistence;
using System;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SBERP.Security.Migrations
{
    /// <inheritdoc />
    public partial class InitialSeedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ---------------------------
            // Create Tables (Generated by EF)
            // ---------------------------
            migrationBuilder.CreateTable(
                name: "AppUserMenus",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    IsHeader = table.Column<bool>(type: "bit", nullable: true),
                    IsModule = table.Column<bool>(type: "bit", nullable: true),
                    IsComponent = table.Column<bool>(type: "bit", nullable: true),
                    CssClass = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    IsRouteLink = table.Column<bool>(type: "bit", nullable: true),
                    RouteLink = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    RouteLinkClass = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Icon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Remark = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    ParentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DropdownIcon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SerialNo = table.Column<int>(type: "int", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserMenus", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUserMenusLog",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserMenuId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    IsHeader = table.Column<bool>(type: "bit", nullable: true),
                    IsModule = table.Column<bool>(type: "bit", nullable: true),
                    IsComponent = table.Column<bool>(type: "bit", nullable: true),
                    CssClass = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    IsRouteLink = table.Column<bool>(type: "bit", nullable: true),
                    RouteLink = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    RouteLinkClass = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Icon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Remark = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    ParentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DropdownIcon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SerialNo = table.Column<int>(type: "int", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true),
                    PerformedUser = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Action = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserMenusLog", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUserProfilesLog",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserProfileId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    FullName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Address = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Email = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    AppUserRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true),
                    PerformedUser = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Action = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserProfilesLog", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUserRoleMenusLog",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserRoleMenuId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AppUserRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AppUserMenuId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsView = table.Column<bool>(type: "bit", nullable: true),
                    IsCreate = table.Column<bool>(type: "bit", nullable: true),
                    IsUpdate = table.Column<bool>(type: "bit", nullable: true),
                    IsDelete = table.Column<bool>(type: "bit", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true),
                    PerformedUser = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Action = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserRoleMenusLog", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUserRoles",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RoleName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Description = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserRoles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUserRolesLog",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RoleName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Description = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true),
                    PerformedUser = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Action = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserRolesLog", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUsersLog",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AppUserProfileId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    UserName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Password = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    SaltKey = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    RefreshToken = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    RefreshTokenExpiryTime = table.Column<DateTime>(type: "datetime", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true),
                    PerformedUser = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Action = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUsersLog", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppUserProfiles",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    FullName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Address = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Email = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    AppUserRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserProfiles", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AppUserProfiles_AppUserRole",
                        column: x => x.AppUserRoleId,
                        principalTable: "AppUserRoles",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "AppUserRoleMenus",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AppUserMenuId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsView = table.Column<bool>(type: "bit", nullable: true),
                    IsCreate = table.Column<bool>(type: "bit", nullable: true),
                    IsUpdate = table.Column<bool>(type: "bit", nullable: true),
                    IsDelete = table.Column<bool>(type: "bit", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUserRoleMenus", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AppUserRoleMenus_AppUserMenu",
                        column: x => x.AppUserMenuId,
                        principalTable: "AppUserMenus",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_AppUserRoleMenus_AppUserRole",
                        column: x => x.AppUserRoleId,
                        principalTable: "AppUserRoles",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "AppUsers",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AppUserProfileId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    UserName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Password = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    SaltKey = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    RefreshToken = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    RefreshTokenExpiryTime = table.Column<DateTime>(type: "datetime", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppUsers", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AppUser_AppUserProfiles",
                        column: x => x.AppUserProfileId,
                        principalTable: "AppUserProfiles",
                        principalColumn: "Id");
                });

            // ---------------------------
            // Execute Functions.sql
            // ---------------------------
            migrationBuilder.Sql(SqlScriptHelper.LoadEmbeddedSql("Functions.sql"));

            // ---------------------------
            // Execute StoredProcedures.sql
            // ---------------------------
            migrationBuilder.Sql(SqlScriptHelper.LoadEmbeddedSql("StoredProcedures.sql"));

            // ---------------------------
            // Execute Triggers.sql
            // ---------------------------
            migrationBuilder.Sql(SqlScriptHelper.LoadEmbeddedSql("Triggers.sql"));

            // ---------------------------
            // Insert Seed Data (Optional)
            // ---------------------------

            migrationBuilder.InsertData(
                table: "AppUserMenus",
                columns: new[] { "Id", "CreatedBy", "CreatedDate", "CssClass", "DropdownIcon", "Icon", "IsActive", "IsComponent", "IsHeader", "IsModule", "IsRouteLink", "Name", "ParentId", "Remark", "RouteLink", "RouteLinkClass", "SerialNo", "UpdatedBy", "UpdatedDate" },
                values: new object[,]
                {
                    { new Guid("0e5e1b9e-840d-4f96-abd1-fdb3efb8a55d"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-item", null, "far fa-circle nav-icon", true, true, false, false, true, "User Role Menu", new Guid("c15215c8-32ca-4182-9510-b57419708a80"), "Navigation Item", "/business/security/appuserrolemenu", "nav-link", 5, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-header", null, "", true, false, true, false, false, "Settings", null, "Header", "", "", 6, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("52f916cc-6c4d-4b4f-b884-4e89f1489b8d"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-item", null, "nav-icon fas fa-cog", true, false, false, true, true, "App Settings", new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"), "Navigation Item", "/business/appsettings", "nav-link active", 7, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("60aadc18-6b91-4cee-ace7-97700b685c98"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-item", null, "far fa-circle nav-icon", true, true, false, false, true, "User Role", new Guid("c15215c8-32ca-4182-9510-b57419708a80"), "Navigation Item", "/business/security/appuserrole", "nav-link", 5, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("904b0d8a-cc96-4930-bb1c-65838af2b2ef"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-item", null, "far fa-circle nav-icon", true, true, false, false, true, "User Menu", new Guid("c15215c8-32ca-4182-9510-b57419708a80"), "Navigation Item", "/business/security/appusermenu", "nav-link", 5, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("c15215c8-32ca-4182-9510-b57419708a80"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-item", "fas fa-angle-left right", "nav-icon fas fa-cog", true, false, false, true, false, "Security", new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"), "Navigation Item", "", "nav-link active", 4, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-header", null, "", true, false, true, false, false, "Home", null, "Header", "", "", 1, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("e8038aef-f00b-4d01-a5d3-99da9cc1a56b"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-item", null, "nav-icon fas fa-tachometer-alt", true, false, false, true, true, "Dashboard", new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"), "Navigation Item", "/business/home", "nav-link active", 2, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) },
                    { new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc), "nav-header", null, "", true, false, true, false, false, "Business", null, "Header", "", "", 3, null, new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc) }
                });

            migrationBuilder.InsertData(
                table: "AppUserRoles",
                columns: new[] { "Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "RoleName", "UpdatedBy", "UpdatedDate" },
                values: new object[,]
                {
                    { new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "1B15CE5A-56B3-4EB9-8286-6E27F770B0DA", new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc), "User", true, "User", null, new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc) },
                    { new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), null, new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc), "Admin", true, "Admin", null, new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc) }
                });

            migrationBuilder.InsertData(
                table: "AppUserProfiles",
                columns: new[] { "Id", "Address", "AppUserRoleId", "CreatedBy", "CreatedDate", "Email", "FullName", "IsActive", "UpdatedBy", "UpdatedDate" },
                values: new object[,]
                {
                    { new Guid("c047d662-9f0e-4358-b323-15ec3081312c"), "Dubai", new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), null, new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc), "sbhowmikcse08@gmail.com", "Sreemonta Bhowmik", true, null, new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc) },
                    { new Guid("efedc118-3459-4c2e-9158-ad69196a59e0"), "Dubai", new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc), "rohine2008@gmail.com", "Anannya Rohine", true, null, new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc) }
                });

            migrationBuilder.InsertData(
                table: "AppUserRoleMenus",
                columns: new[] { "Id", "AppUserMenuId", "AppUserRoleId", "CreatedBy", "CreatedDate", "IsActive", "IsCreate", "IsDelete", "IsUpdate", "IsView", "UpdatedBy", "UpdatedDate" },
                values: new object[,]
                {
                    { new Guid("1122ebc9-40b0-43d1-bd60-f3b0f7666ea3"), new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("1d3bee1c-6126-4113-8599-c64c7f1d47f6"), new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("228de240-db62-4e40-8ef0-367c0f71286d"), new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), false, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("5bca0329-727c-46c1-9c05-7f54292b0b17"), new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("698ece21-fd28-44ba-95f1-1ffef963c5b5"), new Guid("60aadc18-6b91-4cee-ace7-97700b685c98"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, true, true, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("6ee5cff9-9cef-450d-85a7-b9b1fc3b1431"), new Guid("0e5e1b9e-840d-4f96-abd1-fdb3efb8a55d"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, true, false, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("87f5e973-b247-4fa9-8c48-60f3fd6f2021"), new Guid("c15215c8-32ca-4182-9510-b57419708a80"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("8dd17156-46b2-4199-ad17-b32785209468"), new Guid("52f916cc-6c4d-4b4f-b884-4e89f1489b8d"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, true, true, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("90503e10-3fc1-4dc2-a39b-2f2a9aa198f1"), new Guid("60aadc18-6b91-4cee-ace7-97700b685c98"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, true, true, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("9119fbda-76e6-4098-9ada-b0e8b027fc24"), new Guid("52f916cc-6c4d-4b4f-b884-4e89f1489b8d"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), false, true, true, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("b5aaf803-3ba5-4003-804a-c8bb8973a481"), new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("bb58e8fa-60cc-4505-bf83-21495ed9f8e3"), new Guid("904b0d8a-cc96-4930-bb1c-65838af2b2ef"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, true, true, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("dc00dc24-6d35-47ee-8ced-5f119721628e"), new Guid("e8038aef-f00b-4d01-a5d3-99da9cc1a56b"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, false, false, false, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("e7e675a8-f9aa-4def-b952-eee1b18c708a"), new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("eb3008bc-7ef6-42cf-a6af-50e720e47b8e"), new Guid("c15215c8-32ca-4182-9510-b57419708a80"), new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, null, null, null, null, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) },
                    { new Guid("f6f1bfa4-1aa9-45e8-876d-cf1c4d959c38"), new Guid("e8038aef-f00b-4d01-a5d3-99da9cc1a56b"), new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"), "C047D662-9F0E-4358-B323-15EC3081312C", new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc), true, true, true, true, true, null, new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc) }
                });

            migrationBuilder.InsertData(
                table: "AppUsers",
                columns: new[] { "Id", "AppUserProfileId", "CreatedBy", "CreatedDate", "IsActive", "Password", "RefreshToken", "RefreshTokenExpiryTime", "SaltKey", "UpdatedBy", "UpdatedDate", "UserName" },
                values: new object[,]
                {
                    { new Guid("5fd67aaf-183e-48f8-bb53-15b7628a3e0a"), new Guid("c047d662-9f0e-4358-b323-15ec3081312c"), null, new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc), true, "$2b$10$dqPNaHnCGjUcvxXHTRXmDeNwNRQ0YI8kT9376noZw8i8tDj8KKoEa", null, null, "$2b$10$dqPNaHnCGjUcvxXHTRXmDe", null, new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc), "sree" },
                    { new Guid("a9e00f47-89ec-46a3-a5e8-31ebd52ac121"), new Guid("efedc118-3459-4c2e-9158-ad69196a59e0"), null, new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc), true, "$2b$10$dqPNaHnCGjUcvxXHTRXmDeNwNRQ0YI8kT9376noZw8i8tDj8KKoEa", null, null, "$2b$10$dqPNaHnCGjUcvxXHTRXmDe", null, new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc), "rohine" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_AppUserProfiles_AppUserRoleId",
                table: "AppUserProfiles",
                column: "AppUserRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_AppUserRoleMenus_AppUserMenuId",
                table: "AppUserRoleMenus",
                column: "AppUserMenuId");

            migrationBuilder.CreateIndex(
                name: "IX_AppUserRoleMenus_AppUserRoleId",
                table: "AppUserRoleMenus",
                column: "AppUserRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_AppUsers_AppUserProfileId",
                table: "AppUsers",
                column: "AppUserProfileId",
                unique: true,
                filter: "[AppUserProfileId] IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AppUserMenusLog");

            migrationBuilder.DropTable(
                name: "AppUserProfilesLog");

            migrationBuilder.DropTable(
                name: "AppUserRoleMenus");

            migrationBuilder.DropTable(
                name: "AppUserRoleMenusLog");

            migrationBuilder.DropTable(
                name: "AppUserRolesLog");

            migrationBuilder.DropTable(
                name: "AppUsers");

            migrationBuilder.DropTable(
                name: "AppUsersLog");

            migrationBuilder.DropTable(
                name: "AppUserMenus");

            migrationBuilder.DropTable(
                name: "AppUserProfiles");

            migrationBuilder.DropTable(
                name: "AppUserRoles");

            //migrationBuilder.Sql("DROP FUNCTION IF EXISTS dbo.GetChildMenus");
            //// Drop procedures (DO THIS CAREFULLY)
            //migrationBuilder.Sql("DROP PROCEDURE IF EXISTS dbo.SP_CreateUpdateAppUserMenu");
            //migrationBuilder.Sql("DROP PROCEDURE IF EXISTS dbo.SP_CreateUpdateAppUserRoleMenu");

            //// Drop triggers (same idea)
            //migrationBuilder.Sql("DROP TRIGGER IF EXISTS TRG_InsertAppUserMenus");
            //migrationBuilder.Sql("DROP TRIGGER IF EXISTS TRG_UpdateAppUserMenus");
            //migrationBuilder.Sql("DROP TRIGGER IF EXISTS TRG_DeleteAppUserMenus");

            //// You may choose to drop more triggers.
        }
    }
}
