// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBERP.Security.Persistence;

#nullable disable

namespace SBERP.Security.Migrations
{
    [DbContext(typeof(SecurityDBContext))]
    partial class SecurityDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AppUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserProfileId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("SaltKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserProfileId")
                        .IsUnique()
                        .HasFilter("[AppUserProfileId] IS NOT NULL");

                    b.ToTable("AppUsers", t =>
                        {
                            t.HasTrigger("TRG_DeleteAppUsers");

                            t.HasTrigger("TRG_InsertAppUsers");

                            t.HasTrigger("TRG_UpdateAppUsers");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fd67aaf-183e-48f8-bb53-15b7628a3e0a"),
                            AppUserProfileId = new Guid("c047d662-9f0e-4358-b323-15ec3081312c"),
                            CreatedDate = new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Password = "$2b$10$dqPNaHnCGjUcvxXHTRXmDeNwNRQ0YI8kT9376noZw8i8tDj8KKoEa",
                            SaltKey = "$2b$10$dqPNaHnCGjUcvxXHTRXmDe",
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc),
                            UserName = "sree"
                        },
                        new
                        {
                            Id = new Guid("a9e00f47-89ec-46a3-a5e8-31ebd52ac121"),
                            AppUserProfileId = new Guid("efedc118-3459-4c2e-9158-ad69196a59e0"),
                            CreatedDate = new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Password = "$2b$10$dqPNaHnCGjUcvxXHTRXmDeNwNRQ0YI8kT9376noZw8i8tDj8KKoEa",
                            SaltKey = "$2b$10$dqPNaHnCGjUcvxXHTRXmDe",
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc),
                            UserName = "rohine"
                        });
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Action");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserId");

                    b.Property<Guid?>("AppUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserProfileId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PerformedUser");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("SaltKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AppUsersLog");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CssClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DropdownIcon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsComponent")
                        .HasColumnType("bit")
                        .HasColumnName("IsComponent");

                    b.Property<bool?>("IsHeader")
                        .HasColumnType("bit")
                        .HasColumnName("IsHeader");

                    b.Property<bool?>("IsModule")
                        .HasColumnType("bit")
                        .HasColumnName("IsModule");

                    b.Property<bool?>("IsRouteLink")
                        .HasColumnType("bit")
                        .HasColumnName("IsRouteLink");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ParentId");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RouteLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RouteLinkClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SerialNo")
                        .HasColumnType("int")
                        .HasColumnName("SerialNo");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AppUserMenus", t =>
                        {
                            t.HasTrigger("TRG_DeleteAppUserMenus");

                            t.HasTrigger("TRG_InsertAppUserMenus");

                            t.HasTrigger("TRG_UpdateAppUserMenus");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-header",
                            Icon = "",
                            IsActive = true,
                            IsComponent = false,
                            IsHeader = true,
                            IsModule = false,
                            IsRouteLink = false,
                            Name = "Home",
                            Remark = "Header",
                            RouteLink = "",
                            RouteLinkClass = "",
                            SerialNo = 1,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e8038aef-f00b-4d01-a5d3-99da9cc1a56b"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-item",
                            Icon = "nav-icon fas fa-tachometer-alt",
                            IsActive = true,
                            IsComponent = false,
                            IsHeader = false,
                            IsModule = true,
                            IsRouteLink = true,
                            Name = "Dashboard",
                            ParentId = new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"),
                            Remark = "Navigation Item",
                            RouteLink = "/business/home",
                            RouteLinkClass = "nav-link active",
                            SerialNo = 2,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-header",
                            Icon = "",
                            IsActive = true,
                            IsComponent = false,
                            IsHeader = true,
                            IsModule = false,
                            IsRouteLink = false,
                            Name = "Business",
                            Remark = "Header",
                            RouteLink = "",
                            RouteLinkClass = "",
                            SerialNo = 3,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c15215c8-32ca-4182-9510-b57419708a80"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-item",
                            DropdownIcon = "fas fa-angle-left right",
                            Icon = "nav-icon fas fa-cog",
                            IsActive = true,
                            IsComponent = false,
                            IsHeader = false,
                            IsModule = true,
                            IsRouteLink = false,
                            Name = "Security",
                            ParentId = new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"),
                            Remark = "Navigation Item",
                            RouteLink = "",
                            RouteLinkClass = "nav-link active",
                            SerialNo = 4,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60aadc18-6b91-4cee-ace7-97700b685c98"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-item",
                            Icon = "far fa-circle nav-icon",
                            IsActive = true,
                            IsComponent = true,
                            IsHeader = false,
                            IsModule = false,
                            IsRouteLink = true,
                            Name = "User Role",
                            ParentId = new Guid("c15215c8-32ca-4182-9510-b57419708a80"),
                            Remark = "Navigation Item",
                            RouteLink = "/business/security/appuserrole",
                            RouteLinkClass = "nav-link",
                            SerialNo = 5,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("904b0d8a-cc96-4930-bb1c-65838af2b2ef"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-item",
                            Icon = "far fa-circle nav-icon",
                            IsActive = true,
                            IsComponent = true,
                            IsHeader = false,
                            IsModule = false,
                            IsRouteLink = true,
                            Name = "User Menu",
                            ParentId = new Guid("c15215c8-32ca-4182-9510-b57419708a80"),
                            Remark = "Navigation Item",
                            RouteLink = "/business/security/appusermenu",
                            RouteLinkClass = "nav-link",
                            SerialNo = 5,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0e5e1b9e-840d-4f96-abd1-fdb3efb8a55d"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-item",
                            Icon = "far fa-circle nav-icon",
                            IsActive = true,
                            IsComponent = true,
                            IsHeader = false,
                            IsModule = false,
                            IsRouteLink = true,
                            Name = "User Role Menu",
                            ParentId = new Guid("c15215c8-32ca-4182-9510-b57419708a80"),
                            Remark = "Navigation Item",
                            RouteLink = "/business/security/appuserrolemenu",
                            RouteLinkClass = "nav-link",
                            SerialNo = 5,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-header",
                            Icon = "",
                            IsActive = true,
                            IsComponent = false,
                            IsHeader = true,
                            IsModule = false,
                            IsRouteLink = false,
                            Name = "Settings",
                            Remark = "Header",
                            RouteLink = "",
                            RouteLinkClass = "",
                            SerialNo = 6,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("52f916cc-6c4d-4b4f-b884-4e89f1489b8d"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            CssClass = "nav-item",
                            Icon = "nav-icon fas fa-cog",
                            IsActive = true,
                            IsComponent = false,
                            IsHeader = false,
                            IsModule = true,
                            IsRouteLink = true,
                            Name = "App Settings",
                            ParentId = new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"),
                            Remark = "Navigation Item",
                            RouteLink = "/business/appsettings",
                            RouteLinkClass = "nav-link active",
                            SerialNo = 7,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserMenuLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Action");

                    b.Property<Guid>("AppUserMenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserMenuId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CssClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DropdownIcon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsComponent")
                        .HasColumnType("bit")
                        .HasColumnName("IsComponent");

                    b.Property<bool?>("IsHeader")
                        .HasColumnType("bit")
                        .HasColumnName("IsHeader");

                    b.Property<bool?>("IsModule")
                        .HasColumnType("bit")
                        .HasColumnName("IsModule");

                    b.Property<bool?>("IsRouteLink")
                        .HasColumnType("bit")
                        .HasColumnName("IsRouteLink");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ParentId");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PerformedUser");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RouteLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RouteLinkClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SerialNo")
                        .HasColumnType("int")
                        .HasColumnName("SerialNo");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AppUserMenusLog");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("AppUserRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserRoleId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AppUserRoleId");

                    b.ToTable("AppUserProfiles", t =>
                        {
                            t.HasTrigger("TRG_DeleteAppUserProfiles");

                            t.HasTrigger("TRG_InsertAppUserProfiles");

                            t.HasTrigger("TRG_UpdateAppUserProfiles");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c047d662-9f0e-4358-b323-15ec3081312c"),
                            Address = "Dubai",
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedDate = new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            Email = "sbhowmikcse08@gmail.com",
                            FullName = "Sreemonta Bhowmik",
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("efedc118-3459-4c2e-9158-ad69196a59e0"),
                            Address = "Dubai",
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            Email = "rohine2008@gmail.com",
                            FullName = "Anannya Rohine",
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserProfileLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Action");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AppUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserProfileId");

                    b.Property<Guid?>("AppUserRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserRoleId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PerformedUser");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfilesLog");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AppUserRoles", t =>
                        {
                            t.HasTrigger("TRG_DeleteAppUserRoles");

                            t.HasTrigger("TRG_InsertAppUserRoles");

                            t.HasTrigger("TRG_UpdateAppUserRoles");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Admin",
                            IsActive = true,
                            RoleName = "Admin",
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "1B15CE5A-56B3-4EB9-8286-6E27F770B0DA",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User",
                            IsActive = true,
                            RoleName = "User",
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserRoleLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Action");

                    b.Property<Guid>("AppUserRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserRoleId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PerformedUser");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AppUserRolesLog");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserRoleMenuLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Action");

                    b.Property<Guid?>("AppUserMenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserMenuId");

                    b.Property<Guid?>("AppUserRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserRoleId");

                    b.Property<Guid?>("AppUserRoleMenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserRoleMenuId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsCreate")
                        .HasColumnType("bit")
                        .HasColumnName("IsCreate");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IsDelete");

                    b.Property<bool?>("IsUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("IsUpdate");

                    b.Property<bool?>("IsView")
                        .HasColumnType("bit")
                        .HasColumnName("IsView");

                    b.Property<string>("PerformedUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PerformedUser");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("AppUserRoleMenusLog");
                });

            modelBuilder.Entity("SSBERP.Security.Models.Base.AppUserRoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AppUserMenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserMenuId");

                    b.Property<Guid?>("AppUserRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserRoleId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsCreate")
                        .HasColumnType("bit")
                        .HasColumnName("IsCreate");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IsDelete");

                    b.Property<bool?>("IsUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("IsUpdate");

                    b.Property<bool?>("IsView")
                        .HasColumnType("bit")
                        .HasColumnName("IsView");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AppUserMenuId");

                    b.HasIndex("AppUserRoleId");

                    b.ToTable("AppUserRoleMenus", t =>
                        {
                            t.HasTrigger("TRG_DeleteAppUserRoleMenus");

                            t.HasTrigger("TRG_InsertAppUserRoleMenus");

                            t.HasTrigger("TRG_UpdateAppUserRoleMenus");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d3bee1c-6126-4113-8599-c64c7f1d47f6"),
                            AppUserMenuId = new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f6f1bfa4-1aa9-45e8-876d-cf1c4d959c38"),
                            AppUserMenuId = new Guid("e8038aef-f00b-4d01-a5d3-99da9cc1a56b"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = true,
                            IsDelete = true,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5bca0329-727c-46c1-9c05-7f54292b0b17"),
                            AppUserMenuId = new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("87f5e973-b247-4fa9-8c48-60f3fd6f2021"),
                            AppUserMenuId = new Guid("c15215c8-32ca-4182-9510-b57419708a80"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("698ece21-fd28-44ba-95f1-1ffef963c5b5"),
                            AppUserMenuId = new Guid("60aadc18-6b91-4cee-ace7-97700b685c98"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = true,
                            IsDelete = true,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e7e675a8-f9aa-4def-b952-eee1b18c708a"),
                            AppUserMenuId = new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8dd17156-46b2-4199-ad17-b32785209468"),
                            AppUserMenuId = new Guid("52f916cc-6c4d-4b4f-b884-4e89f1489b8d"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = true,
                            IsDelete = true,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1122ebc9-40b0-43d1-bd60-f3b0f7666ea3"),
                            AppUserMenuId = new Guid("db0085b7-695d-4751-a190-6c52e3bb44f1"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dc00dc24-6d35-47ee-8ced-5f119721628e"),
                            AppUserMenuId = new Guid("e8038aef-f00b-4d01-a5d3-99da9cc1a56b"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = false,
                            IsDelete = false,
                            IsUpdate = false,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bb58e8fa-60cc-4505-bf83-21495ed9f8e3"),
                            AppUserMenuId = new Guid("904b0d8a-cc96-4930-bb1c-65838af2b2ef"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = true,
                            IsDelete = true,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("90503e10-3fc1-4dc2-a39b-2f2a9aa198f1"),
                            AppUserMenuId = new Guid("60aadc18-6b91-4cee-ace7-97700b685c98"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = true,
                            IsDelete = true,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("228de240-db62-4e40-8ef0-367c0f71286d"),
                            AppUserMenuId = new Guid("52d7e13b-ef24-4f17-937b-d6e8005a6658"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eb3008bc-7ef6-42cf-a6af-50e720e47b8e"),
                            AppUserMenuId = new Guid("c15215c8-32ca-4182-9510-b57419708a80"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9119fbda-76e6-4098-9ada-b0e8b027fc24"),
                            AppUserMenuId = new Guid("52f916cc-6c4d-4b4f-b884-4e89f1489b8d"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            IsCreate = true,
                            IsDelete = true,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6ee5cff9-9cef-450d-85a7-b9b1fc3b1431"),
                            AppUserMenuId = new Guid("0e5e1b9e-840d-4f96-abd1-fdb3efb8a55d"),
                            AppUserRoleId = new Guid("1b15ce5a-56b3-4eb9-8286-6e27f770b0da"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsCreate = true,
                            IsDelete = false,
                            IsUpdate = true,
                            IsView = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b5aaf803-3ba5-4003-804a-c8bb8973a481"),
                            AppUserMenuId = new Guid("f0f0183b-7f60-4eb4-97d8-d2c15a4ae62c"),
                            AppUserRoleId = new Guid("10a9e9e7-cb24-4816-9b94-9db275a40edd"),
                            CreatedBy = "C047D662-9F0E-4358-B323-15EC3081312C",
                            CreatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedDate = new DateTime(2024, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUser", b =>
                {
                    b.HasOne("SBERP.Security.Models.Base.AppUserProfile", "AppUserProfile")
                        .WithOne("AppUser")
                        .HasForeignKey("SBERP.Security.Models.Base.AppUser", "AppUserProfileId")
                        .HasConstraintName("FK_AppUser_AppUserProfiles");

                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserProfile", b =>
                {
                    b.HasOne("SBERP.Security.Models.Base.AppUserRole", "AppUserRole")
                        .WithMany("AppUserProfiles")
                        .HasForeignKey("AppUserRoleId")
                        .HasConstraintName("FK_AppUserProfiles_AppUserRole");

                    b.Navigation("AppUserRole");
                });

            modelBuilder.Entity("SSBERP.Security.Models.Base.AppUserRoleMenu", b =>
                {
                    b.HasOne("SBERP.Security.Models.Base.AppUserMenu", "AppUserMenu")
                        .WithMany("AppUserRoleMenus")
                        .HasForeignKey("AppUserMenuId")
                        .HasConstraintName("FK_AppUserRoleMenus_AppUserMenu");

                    b.HasOne("SBERP.Security.Models.Base.AppUserRole", "AppUserRole")
                        .WithMany("AppUserRoleMenus")
                        .HasForeignKey("AppUserRoleId")
                        .HasConstraintName("FK_AppUserRoleMenus_AppUserRole");

                    b.Navigation("AppUserMenu");

                    b.Navigation("AppUserRole");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserMenu", b =>
                {
                    b.Navigation("AppUserRoleMenus");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserProfile", b =>
                {
                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SBERP.Security.Models.Base.AppUserRole", b =>
                {
                    b.Navigation("AppUserProfiles");

                    b.Navigation("AppUserRoleMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
